Translate 97
SeonHyungJo/reactjs-interview-questions-korean pull request #100
Opened 2019-07-04 10:28 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-06 13:02 UTC, BKJang commented on README.md
> +|97 | [왜 ReactDOM는 React과 분리되어 있나?](#왜-ReactDOM는-React과-분리되어-있나) |
> 왜 ReactDOM은 React와 분리되어 있나?

가 자연스러울 것 같습니다.

2019-07-06 13:02 UTC, BKJang commented on README.md
> +97. ### 왜 ReactDOM는 React과 분리되어 있나?
위와 동일합니다 :)

2019-07-06 13:02 UTC, BKJang requested changes
수정 요청합니다!

2019-07-06 15:23 UTC, SeonHyungJo commented on README.md
> +|97 | [왜 ReactDOM는 React과 분리되어 있나?](#왜-ReactDOM는-React과-분리되어-있나) |
**왜 ReactDOM는 React과 분리되어 있나?**

보다는 내용상 

**왜 ReactDOM는 React과 분리되었나?**

도 괜찮아 보입니다. 어떤가요?

2019-07-07 02:45 UTC, BKJang commented on README.md
> +|97 | [왜 ReactDOM는 React과 분리되어 있나?](#왜-ReactDOM는-React과-분리되어-있나) |
네 좋은 것 같습니다 는 보다는 은 과 보다는 와가 더 맞을 것 같습니다 이 부분도 같이 수정해주시면 감사하겠습니다 :)

2019-07-07 06:29 UTC, SeonHyungJo commented on README.md
> +|97 | [왜 ReactDOM는 React과 분리되어 있나?](#왜-ReactDOM는-React과-분리되어-있나) |
반영하였습니다. 👍

2019-07-07 06:29 UTC, SeonHyungJo commented on README.md
> +97. ### 왜 ReactDOM는 React과 분리되어 있나?
반영하였습니다. 👍

2019-07-07 06:30 UTC, BKJang approved these changes
승인합니다 👍

2019-07-07 06:30 UTC, merged