Translate 99
SeonHyungJo/reactjs-interview-questions-korean pull request #102
Opened 2019-07-04 10:30 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-06 13:04 UTC, BKJang commented on README.md
> +|99 | [여러 개의 인라인 스타일 개체를 결합하는 방법은?](#여러-개의-인라인-스타일-개체를-결합하는-방법은) |
영문이 object인 만큼 `객체`가 좀 더 정확한 표현이지 않을까요?

2019-07-06 13:04 UTC, BKJang commented on README.md
> +99. ### 여러 개의 인라인 스타일 개체를 결합하는 방법은?
위와 동일합니다 :)

2019-07-06 13:04 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-06 15:27 UTC, SeonHyungJo commented on README.md
> +|99 | [여러 개의 인라인 스타일 개체를 결합하는 방법은?](#여러-개의-인라인-스타일-개체를-결합하는-방법은) |
수정하였습니다. 확인 부탁드립니다. 🙏

2019-07-06 15:27 UTC, SeonHyungJo commented on README.md
> +99. ### 여러 개의 인라인 스타일 개체를 결합하는 방법은?
수정하였습니다. 확인 부탁드립니다. 🙏

2019-07-07 02:47 UTC, BKJang approved these changes
승인합니다 👍

2019-07-07 02:47 UTC, merged