Translate 110
SeonHyungJo/reactjs-interview-questions-korean pull request #113
Opened 2019-07-05 14:30 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-06 13:17 UTC, BKJang commented on README.md
> +110. ### 브라우저 런타임에 React 버번을 어떻게 알 수 있나?
오타 수정바랍니다. (`버번` => `버전)

2019-07-06 13:17 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-06 15:27 UTC, SeonHyungJo commented on README.md
> +110. ### 브라우저 런타임에 React 버번을 어떻게 알 수 있나?
수정하였습니다. 확인 부탁드립니다. 🙏

2019-07-07 02:48 UTC, BKJang approved these changes
승인합니다 👍

2019-07-07 02:48 UTC, merged