Translate 117
SeonHyungJo/reactjs-interview-questions-korean pull request #120
Opened 2019-07-08 15:01 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-09 10:24 UTC, BKJang commented on README.md
> +     내보내기 지정자를 사용하면 MyProfile이 멤버가 되어 이 모듈로 내보낼 수 있으며, 다른 컴포넌트에 이름을 언급하지 않고도 가져올 수 있다.
내보내기 지정자 보다는 export를 그대로 영문 표기해주는 것이 어떨까요?

2019-07-09 10:24 UTC, BKJang requested changes
수정요청합니다 😄

2019-07-10 12:56 UTC, SeonHyungJo commented on README.md
> +     내보내기 지정자를 사용하면 MyProfile이 멤버가 되어 이 모듈로 내보낼 수 있으며, 다른 컴포넌트에 이름을 언급하지 않고도 가져올 수 있다.
반영하였습니다. 확인부탁드립니다. 🙏

2019-07-11 10:07 UTC, BKJang approved these changes
승인합니다 👍

2019-07-11 10:10 UTC, merged