Translate 120
SeonHyungJo/reactjs-interview-questions-korean pull request #123
Opened 2019-07-08 15:19 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-09 14:34 UTC, BKJang commented on README.md
> +     *Static fields*는 *Class Fields* 스테이지 3 제안 일부이다.
`스테이지 3 제안 일부이다.` => `스테이지 3 제안의 일부이다.`로 바꾸는게 자연스러운 표현이 될 것 같습니다.

2019-07-09 14:35 UTC, BKJang requested changes
수정 요청합니다 😄

2019-07-10 12:56 UTC, SeonHyungJo commented on README.md
> +     *Static fields*는 *Class Fields* 스테이지 3 제안 일부이다.
반영하였습니다. 확인부탁드립니다. 🙏

2019-07-11 10:10 UTC, BKJang approved these changes
승인합니다 👍

2019-07-11 10:11 UTC, merged