🔖 BKJang / Translate / Translate-40
SeonHyungJo/reactjs-interview-questions-korean pull request #134
Opened 2019-07-13 08:08 UTC by BKJang

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-13 15:20 UTC, SeonHyungJo commented on README.md
> +    자식 클래스 생성자는`super()`메소드가 호출 될 때까지`this`를 참조할 수 없습니다. ES6 하위 클래스에도 동일하게 적용된다. super() 호출에 props 매개 변수를 전달하는 주요한 이유는 자식 생성자에서 `this.props`에 접근하기 위해서다.
```suggestion
    자식 클래스 생성자는`super()`메서드가 호출 될 때까지 `this`를 참조할 수 없습니다. ES6 하위 클래스에도 동일하게 적용된다. super() 호출에 props 매개 변수를 전달하는 주요한 이유는 자식 생성자에서 `this.props`에 접근하기 위해서다.
```
해당 메소드에 대하며 명세에 따라 `메서드`로 변경을 요청합니다.

[번역 가이드](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/wiki/Translate-Glossary)

2019-07-13 15:21 UTC, SeonHyungJo requested changes
확인부탁드립니다. 🙏

2019-07-14 13:28 UTC, BKJang commented on README.md
> +    자식 클래스 생성자는`super()`메소드가 호출 될 때까지`this`를 참조할 수 없습니다. ES6 하위 클래스에도 동일하게 적용된다. super() 호출에 props 매개 변수를 전달하는 주요한 이유는 자식 생성자에서 `this.props`에 접근하기 위해서다.
수정완료하였습니다. 확인부탁드립니다 🙏

2019-07-15 00:17 UTC, SeonHyungJo commented
머지했습니다. 👍

2019-07-15 00:17 UTC, merged