Translate-171
SeonHyungJo/reactjs-interview-questions-korean pull request #165
Opened 2019-09-15 08:00 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-09-16 12:20 UTC, BKJang commented on README.md
> +     상수를 사용하면 IDE를 사용할 때 프로젝트 전체에서 특정 기능의 모든 사용법을 쉽게 찾을 수 있다. 또한 오타로 인해 버그가 발생하는 것을 방지한다. - 이러한 경우, 즉시 `ReferenceError` 가 발생한다.
```suggestion
     상수를 사용하면 IDE를 사용할 때 프로젝트 전체에서 특정 기능의 모든 사용법을 쉽게 찾을 수 있다. 또한 오타로 인해 `ReferenceError`와 같은 버그가 발생하는 것을 방지한다.
```

위와 같이 표현을 수정하는게 더 자연스러울 것 같은데 어떠신가요?

2019-09-16 12:21 UTC, BKJang requested changes
약간의 수정과 관련하여 제안드립니다 :)

2019-09-17 00:22 UTC, SeonHyungJo commented on README.md
> +     상수를 사용하면 IDE를 사용할 때 프로젝트 전체에서 특정 기능의 모든 사용법을 쉽게 찾을 수 있다. 또한 오타로 인해 버그가 발생하는 것을 방지한다. - 이러한 경우, 즉시 `ReferenceError` 가 발생한다.
```suggestion
     상수를 사용하면 IDE를 사용할 때 프로젝트 전체에서 특정 기능의 모든 사용법을 쉽게 찾을 수 있다. 오타같은 경우 `ReferenceError` 를 던져주어 버그 발생을 사전에 방지한다.
```

`ReferenceError와 같은` 이라는 문장이 어울리지 않아 좀 더 수정을 제안합니다. @BKJang

2019-09-17 10:28 UTC, BKJang commented on README.md
> +     상수를 사용하면 IDE를 사용할 때 프로젝트 전체에서 특정 기능의 모든 사용법을 쉽게 찾을 수 있다. 또한 오타로 인해 버그가 발생하는 것을 방지한다. - 이러한 경우, 즉시 `ReferenceError` 가 발생한다.
넵 좋은 의견입니다 👍

2019-09-17 12:29 UTC, merged