Translate-202
SeonHyungJo/reactjs-interview-questions-korean pull request #192
Opened 2019-10-09 10:05 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-10-09 11:16 UTC, BKJang commented on README.md
> +|202| [ Styled Components란?](#Styled-Components란) |
```suggestion
|202| [Styled Components란?](#Styled-Components란) |
```

2019-10-09 11:19 UTC, BKJang commented on README.md
> +     `styled-components`는 React 애플리케이션 스타일링을 위한 JavaScript 라이브러리이다. 스타일과 컴포넌트 간의 매핑을 제거하고 JavaScript로 보강된 실제 CSS를 작성할 수 있다.
```suggestion
     `styled-components`는 React 애플리케이션 스타일링을 위한 JavaScript 라이브러리이다. 스타일과 컴포넌트 간의 매핑을 제거하고 JavaScript로 실제 CSS를 작성할 수 있다.
```
'보강된'이라는 의미를 어디서 해석하셨는지 물어봐도 될까요?

2019-10-09 11:19 UTC, BKJang requested changes
확인 부탁드립니다 :)

2019-10-09 12:07 UTC, SeonHyungJo commented on README.md
> +     `styled-components`는 React 애플리케이션 스타일링을 위한 JavaScript 라이브러리이다. 스타일과 컴포넌트 간의 매핑을 제거하고 JavaScript로 보강된 실제 CSS를 작성할 수 있다.
```
It removes the mapping between styles and components, and lets you write actual CSS augmented with JavaScript.
```
단순히 자바스크립트로 CSS를 작성한다기 보다는 한층더 보강된 모양으로 작성한다는 의미의 단어로 해석했습니다.

2019-10-10 09:30 UTC, BKJang commented on README.md
> +     `styled-components`는 React 애플리케이션 스타일링을 위한 JavaScript 라이브러리이다. 스타일과 컴포넌트 간의 매핑을 제거하고 JavaScript로 보강된 실제 CSS를 작성할 수 있다.
네 좋은 의견인 것 같습니다 👍

2019-10-10 09:32 UTC, BKJang approved these changes
승인합니다 👍

2019-10-10 09:32 UTC, merged