Translate-213
SeonHyungJo/reactjs-interview-questions-korean pull request #203
Opened 2019-10-17 13:40 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-10-24 10:17 UTC, BKJang commented on README.md
> +|213| [React PropTypes이 하나의 prop에서 다른 타입들은 허용하는 방법은?](#React-PropTypes이-하나의-prop에서-다른-타입들은-허용하는-방법은) |
```suggestion
|213| [React PropTypes가 하나의 prop에서 다른 타입들은 허용하는 방법은?](#React-PropTypes가-하나의-prop에서-다른-타입들은-허용하는-방법은) |
```

2019-10-24 10:17 UTC, BKJang commented on README.md
> +8.   ### React PropTypes이 하나의 prop에서 다른 타입들은 허용하는 방법은?
```suggestion
8.   ### React PropTypes가 하나의 prop에서 다른 타입들은 허용하는 방법은?
```

2019-10-24 10:17 UTC, BKJang requested changes
`propTypes가`가 맞는 표현일 것 같습니다.
혹시 어떻게 읽고 해석하셨는지 알려주시면 좋을 것 같습니다 :)

2019-10-25 05:39 UTC, SeonHyungJo commented
> `propTypes가`가 맞는 표현일 것 같습니다.
> 혹시 어떻게 읽고 해석하셨는지 알려주시면 좋을 것 같습니다 :)

이게 말씀해주신 것도 의미가 비슷하면서 오히려 `이(가)`의 잘못보다는 `다른 타입들을`로 바꾸는게 더욱 나아보이네요.

2019-11-06 08:57 UTC, BKJang commented
> > `propTypes가`가 맞는 표현일 것 같습니다.
> > 혹시 어떻게 읽고 해석하셨는지 알려주시면 좋을 것 같습니다 :)
> 
> 이게 말씀해주신 것도 의미가 비슷하면서 오히려 `이(가)`의 잘못보다는 `다른 타입들을`로 바꾸는게 더욱 나아보이네요. @BKJang
> 
> 그리고 저의 경우 한국말로 읽었을때 `리액트 프로토타입이 프로프에서` 라는 식의 표현이 자연스러워서 그렇게 해석을 진행하였습니다.

정작 다른 오타는 찾지 못했네요;;
말씀하신대로 독자마다 다르게 읽을 수 있을 것 같으니 오타만 수정해주시고 나머진 그대로 진행해주시면 될 것 같아요

2019-11-08 14:14 UTC, SeonHyungJo commented
해당 내용을 `다른 타입들을`로 수정하여 반영하였습니다. 확인부탁드립니다.
@BKJang

2019-11-09 12:23 UTC, BKJang approved these changes
승인합니다 👍

2019-11-09 12:24 UTC, merged