Translate-232
SeonHyungJo/reactjs-interview-questions-korean pull request #222
Opened 2019-12-19 15:03 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-12-20 09:45 UTC, BKJang commented on README.md
> +|232| [어떤 시나리오에서 오류를 포착하지 못하나?](#어떤 시나리오에서 오류를 포착하지 못하나)|
```suggestion
|232| [에러 바운더리(error boundary)에서는 어떤 경우 에러를 잡지 못할까?)|
```
위와 같이 표현하는게 좀 더 자연스러울 것 같습니다. 어떠신가요?

2019-12-20 09:46 UTC, BKJang commented on README.md
> +27.  ### 어떤 시나리오에서 오류를 포착하지 못하나?
위와 같은 의견입니다 :)

2019-12-20 09:46 UTC, BKJang requested changes
의견 주시면 감사하겠습니다 😄

2019-12-31 01:48 UTC, SeonHyungJo commented on README.md
> +|232| [어떤 시나리오에서 오류를 포착하지 못하나?](#어떤 시나리오에서 오류를 포착하지 못하나)|
@BKJang 님 의견대로 위와 같은 표기법이 더욱 좋아보이네요. 이 이후에 나오는 내용에 관련하여 추가적인 수정이 필요하겠네요.

2019-12-31 17:04 UTC, SeonHyungJo commented on README.md
> +27.  ### 어떤 시나리오에서 오류를 포착하지 못하나?
적용완료하였습니다. 확인 부탁드립니다. @BKJang

2020-01-01 06:27 UTC, BKJang approved these changes
승인합니다 👍

2020-01-01 06:28 UTC, merged