Translate 233
SeonHyungJo/reactjs-interview-questions-korean pull request #223
Opened 2019-12-19 15:04 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-12-20 09:48 UTC, BKJang commented on README.md
> +|233| [이벤트 핸들러에 오류 경계가 필요하지 않은 이유는?](#이벤트-핸들러에-오류-경계가-필요하지-않은-이유는)|
```suggestion
|233| [이벤트 핸들러에 에러 바운더리가 필요하지 않은 이유는?](#이벤트-핸들러에-에러-바운더리가-필요하지-않은-이유는)|
```
실제로 Error Boundary를 표현할 때 그대로 표현하는 경우가 더 많은 것 같은데 어떻게 생각하시나요? 아니면 영어와 함께 병기하는 것도 좋을 것 같습니다.

2019-12-20 09:49 UTC, BKJang commented on README.md
> +28.  ### 이벤트 핸들러에 오류 경계가 필요하지 않은 이유는?
전체적으로 ErrorBoundary에 대한 표현이 정확히 정해지면 수정하시거나 그대로 진행하시거나 하는게 좋을 것 같습니다.
의견 주세요! 😄

2019-12-31 17:06 UTC, SeonHyungJo commented on README.md
> +|233| [이벤트 핸들러에 오류 경계가 필요하지 않은 이유는?](#이벤트-핸들러에-오류-경계가-필요하지-않은-이유는)|
적용하였습니다. 확인부탁드립니다.

2019-12-31 17:07 UTC, SeonHyungJo commented on README.md
> +28.  ### 이벤트 핸들러에 오류 경계가 필요하지 않은 이유는?
적용하였습니다. 확인부탁드립니다.

2020-01-01 06:28 UTC, BKJang commented on README.md
> +     위의 코드는 오류 경계 대신 바닐라 자바스크립트 try / catch 블록을 사용해서 오류를 잡아내고 있다.
해당 내용도 수정 부탁드립니다 :)

2020-01-01 06:29 UTC, BKJang requested changes
제목과 동일하게 내용도 수정부탁드립니다.

2020-01-01 09:25 UTC, SeonHyungJo commented on README.md
> +     위의 코드는 오류 경계 대신 바닐라 자바스크립트 try / catch 블록을 사용해서 오류를 잡아내고 있다.
적용하였습니다. 확인부탁드립니다. 🙏

2020-01-02 09:56 UTC, BKJang approved these changes
승인합니다 👍

2020-01-02 09:57 UTC, merged