Translate 235
SeonHyungJo/reactjs-interview-questions-korean pull request #225
Opened 2019-12-19 15:04 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2020-01-01 06:31 UTC, BKJang commented on README.md
> +     React 16에서 오류 경계에 잡히지 않는 오류는 React 컴포넌트 tree를 마운트 해제한다. 이렇게 되는 이유는 손상된 UI를 완전히 제거하는 것보다 손상된 UI를 그대로 두는 것이 더 안 좋기 때문이다. 예를 들어, 결제 앱이 잘못된 금액을 표기하는 것보다 렌더링하지 않는 것이 낫다.
```suggestion
     React 16에서 에러 바운더리에 잡히지 않는 오류는 React 컴포넌트 tree를 마운트 해제한다. 이렇게 되는 이유는 손상된 UI를 완전히 제거하는 것보다 손상된 UI를 그대로 두는 것이 더 안 좋기 때문이다. 예를 들어, 결제 앱이 잘못된 금액을 표기하는 것보다 렌더링하지 않는 것이 낫다.
```

2020-01-01 06:31 UTC, BKJang requested changes
해당 글도 전 글들과 마찬가지로 오류 => 에러 바운더리로 정정 부탁드립니다 :)

2020-01-01 09:30 UTC, SeonHyungJo commented
@BKJang 확인부탁드립니다.

2020-01-02 10:00 UTC, BKJang approved these changes
승인합니다 👍

2020-01-02 10:00 UTC, merged