Translate 238
SeonHyungJo/reactjs-interview-questions-korean pull request #228
Opened 2020-03-31 14:53 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2020-04-01 15:17 UTC, BKJang commented on README.md
> +     render() 메서드는 클래스 컴포넌트에서 유일하게 필요로하는 메서드이다. 즉, render 메서드 외 모든 메서드는 클래스 컴포넌트에서 선택사항이다.
```suggestion
     render() 메서드는 클래스 컴포넌트에서 유일하게 필요한 메서드이다. 즉, render 메서드를 제외한 모든 메서드는 클래스 컴포넌트에서 선택사항이다.
```

다음과 같이 제안드립니다 :)

2020-04-01 15:17 UTC, BKJang requested changes
제안드립니다 :)

2020-04-01 15:51 UTC, SeonHyungJo commented on README.md
> +     render() 메서드는 클래스 컴포넌트에서 유일하게 필요로하는 메서드이다. 즉, render 메서드 외 모든 메서드는 클래스 컴포넌트에서 선택사항이다.
좋은의견 같습니다. 해당 내용은 반영하겠습니다. 👍

2020-04-02 15:02 UTC, BKJang approved these changes
승인합니다 👍

2020-04-02 15:02 UTC, merged