Translate 244
SeonHyungJo/reactjs-interview-questions-korean pull request #234
Opened 2020-04-01 15:11 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2020-04-01 15:30 UTC, BKJang commented on README.md
> +     위의 라이프사이클 메서드를 사용하여 오류 바운더리 사용 사례를 데모 목적으로 사용하겠습니다.
```suggestion
     위의 라이프사이클 메서드를 사용하여 오류 바운더리 사용 사례의 데모를 구현했다.
```
이와 같이 표현하는건 어떨까요?

2020-04-01 15:30 UTC, BKJang requested changes
제안드립니다 :)

2020-04-01 15:53 UTC, SeonHyungJo commented on README.md
> +     위의 라이프사이클 메서드를 사용하여 오류 바운더리 사용 사례를 데모 목적으로 사용하겠습니다.
오히려 예시가 있다는 식의 말이 어울려 보이네요.
위돠 같이 에시가 있다 는 어떨까요? @BKJang

2020-04-02 15:04 UTC, BKJang commented on README.md
> +     위의 라이프사이클 메서드를 사용하여 오류 바운더리 사용 사례를 데모 목적으로 사용하겠습니다.
@SeonHyungJo 좋은 것 같습니다 👍

2020-04-07 12:41 UTC, SeonHyungJo commented on README.md
> +     위의 라이프사이클 메서드를 사용하여 오류 바운더리 사용 사례를 데모 목적으로 사용하겠습니다.
반영하였습니다. 확인부탁드립니다. 🙏

2020-04-08 14:27 UTC, BKJang approved these changes
고생하셨습니다 👍

2020-04-08 14:27 UTC, merged