Translate 60
SeonHyungJo/reactjs-interview-questions-korean pull request #63
Opened 2019-06-27 13:55 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-06-29 07:01 UTC, BKJang commented on README.md
> +    `dangerouslySetInnerHTML`는 브라우저 DOM에서 `innerHTML`를 사용하기 위한 React의 대체 속성이다. 마치 `innerHTML`처럼, 크로스-사이트 스크립팅(XSS) 공격을 고려하여 이 속성을 사용하는 것은 위험하다. `__html` 객체를 키로 전달하고 HTML 텍스트를 값으로 전달하면 된다.
> 마치 `innerHTML`처럼, 크로스-사이트 스크립팅(XSS) 공격을 고려하여 이 속성을 사용하는 것은 위험하다.

> `innerHTML`과 같이, 크로스-사이트 스크립팅(XSS) 공격을 고려하여 이 속성을 사용하는 것은 위험하다.

위와 같이 수정하는 것이 좀 더 자연스러울 것 같습니다.

2019-06-29 07:02 UTC, BKJang requested changes
피드백 반영 바랍니다 :)

2019-07-01 13:04 UTC, SeonHyungJo commented on README.md
> +    `dangerouslySetInnerHTML`는 브라우저 DOM에서 `innerHTML`를 사용하기 위한 React의 대체 속성이다. 마치 `innerHTML`처럼, 크로스-사이트 스크립팅(XSS) 공격을 고려하여 이 속성을 사용하는 것은 위험하다. `__html` 객체를 키로 전달하고 HTML 텍스트를 값으로 전달하면 된다.
수정하여 반영하였습니다. 확인부탁드립니다. 🙏

2019-07-01 16:22 UTC, BKJang approved these changes
승인합니다 👍

2019-07-01 16:22 UTC, merged