Translate 72
SeonHyungJo/reactjs-interview-questions-korean pull request #75
Opened 2019-07-02 11:34 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-03 15:21 UTC, BKJang commented on README.md
> +    Webpack의 `DefinePlugin` 메서드를 사용해서 `NODE_ENV`를 `production` 환경으로 설정해야 propType 유효성 검사 및 추가 경고와 같은 사항을 제거할 수 있다. 이와는 별개로, Uglify의 개발 코드와 주석을 제거하는 데드 코드 제거 기능을 사용하여 번들 크기를 크게 줄일 수 있다.
`데드 코드 제거 기능`는 영문과 병기해주는건 어떨까요?

2019-07-03 15:22 UTC, BKJang requested changes
피드백합니다.

2019-07-04 09:08 UTC, SeonHyungJo commented on README.md
> +    Webpack의 `DefinePlugin` 메서드를 사용해서 `NODE_ENV`를 `production` 환경으로 설정해야 propType 유효성 검사 및 추가 경고와 같은 사항을 제거할 수 있다. 이와는 별개로, Uglify의 개발 코드와 주석을 제거하는 데드 코드 제거 기능을 사용하여 번들 크기를 크게 줄일 수 있다.
한글을 우선으로 하면 영문을 추가적으로 병기하였습니다. ✔️

2019-07-05 01:26 UTC, BKJang approved these changes
승인합니다

2019-07-05 01:26 UTC, merged