Translate 80
SeonHyungJo/reactjs-interview-questions-korean pull request #83
Opened 2019-07-02 12:25 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-03 15:31 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-03 15:31 UTC, BKJang commented on README.md
> +    11. `onClickSubmit()` 또는 `onChangeDescription()`과 같은 핸들러 또는 이벤트 핸들러를 클릭해라.
영문 번역 상 `클릭해라`가 맞긴 하지만 다른 문장과 동일하게 `클릭` 정도로 끊어주는 것이 좀 더 자연스러울 것 같습니다.

2019-07-04 09:09 UTC, SeonHyungJo commented on README.md
> +    11. `onClickSubmit()` 또는 `onChangeDescription()`과 같은 핸들러 또는 이벤트 핸들러를 클릭해라.
반영하였습니다. 확인바랍니다. 🙏

2019-07-05 01:26 UTC, BKJang approved these changes
승인합니다 👍

2019-07-05 01:27 UTC, merged