Translate 83
SeonHyungJo/reactjs-interview-questions-korean pull request #86
Opened 2019-07-03 09:49 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-03 15:34 UTC, BKJang commented on README.md
> +    위의 예제에서, *엄격 모드* 검사는 `<ComponentOne>`와 `<ComponentTwo>` 컴포넌트에만 적용된다.
`엄격 모드`라는 표현보다는 위에서와 같이 `strict mode`로 통일해주는게 좋을 듯 합니다.

2019-07-03 15:34 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-04 09:13 UTC, SeonHyungJo commented on README.md
> +    위의 예제에서, *엄격 모드* 검사는 `<ComponentOne>`와 `<ComponentTwo>` 컴포넌트에만 적용된다.
반영완료하였습니다. 확인부탁드립니다. 🙏

2019-07-05 01:27 UTC, BKJang approved these changes
승인합니다 👍

2019-07-05 01:27 UTC, merged