Translate 88
SeonHyungJo/reactjs-interview-questions-korean pull request #91
Opened 2019-07-03 10:42 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-03 15:42 UTC, BKJang commented on README.md
> +    예. 과거에 React는 알 수 없는 DOM 속성을 무시하고 했다. React가 인식하지 못하는 속성을 가진 JSX를 작성했다면 React는 그냥 건너뛸 것이다. 예를 들면, 다음과 같다.
> 그렇다. 과거에 React는 알 수 없는 DOM 속성을 무시하곤 했다. React가 인식하지 못하는 속성을 가진 JSX를 작성했다면 React는 그냥 건너뛸 것이다. 예를 들면, 다음과 같다.`

2019-07-03 15:42 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-04 09:16 UTC, SeonHyungJo commented on README.md
> +    예. 과거에 React는 알 수 없는 DOM 속성을 무시하고 했다. React가 인식하지 못하는 속성을 가진 JSX를 작성했다면 React는 그냥 건너뛸 것이다. 예를 들면, 다음과 같다.
`그렇다`의 표현이 약간 어색함이 느껴지지만 반영하여 올렸습니다. 확인부탁드립니다. 🙏

2019-07-05 01:28 UTC, BKJang approved these changes
승인합니다 👍

2019-07-05 01:28 UTC, merged