Translate 96
SeonHyungJo/reactjs-interview-questions-korean pull request #99
Opened 2019-07-04 10:26 UTC by SeonHyungJo

# Progress

- [x] [번역 리스트 할당 여부 확인(Confirm translation list assignment)](https://github.com/SeonHyungJo/reactjs-interview-questions-korean/issues/2)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2019-07-06 13:00 UTC, BKJang commented on README.md
> +|96 | [ReactDOM과 ReactDOM의 차이점은?](#ReactDOM과-ReactDOM의-차이점은) |
`React와 ReactDOM의 차이점`으로 수정해주세요

2019-07-06 13:00 UTC, BKJang commented on README.md
> +96. ### ReactDOM과 ReactDOM의 차이점은?
위와 동일합니다 :)

2019-07-06 13:01 UTC, BKJang requested changes
수정 요청합니다 :)

2019-07-06 15:22 UTC, SeonHyungJo commented on README.md
> +|96 | [ReactDOM과 ReactDOM의 차이점은?](#ReactDOM과-ReactDOM의-차이점은) |
수정하였습니다. 확인 부탁드립니다. 🙏

2019-07-06 15:22 UTC, SeonHyungJo commented on README.md
> +96. ### ReactDOM과 ReactDOM의 차이점은?
수정하였습니다. 확인 부탁드립니다. 🙏

2019-07-07 02:46 UTC, BKJang approved these changes
승인합니다 👍

2019-07-07 02:46 UTC, merged